### ISSUE TITLE
Aidbox FHIR API returns questionnaire's extesion values in aidbox format with $assemble operation

### ISSUE THREAD

**Issue by qscgyjqscgyj** [beda-software/fhir-sdc#61]
**Here is a questionnaire:**
<img width="916" alt="Screenshot 2024-08-14 at 12 15 11" src="https://github.com/user-attachments/assets/dd22dd73-1801-48ef-a02c-979b8610e322">

By requesting it trough /fhir/Questionnaire/4e3ca838-f83b-4489-a5c9-c782824d672d/$assemble it returns

`{"url": "http://forms.aidbox.io/questionnaire/new-form", "item": [{"text": "Quantity Input", "type": "quantity", "linkId": "pyxzJPuJ", "extension": [{"url": "http://hl7.org/fhir/StructureDefinition/questionnaire-unitOption", "value": {"Coding": {"display": "F"}}}]}], "meta": {"profile": ["https://beda.software/beda-emr-questionnaire"], "lastUpdated": "2024-08-13T11:47:15.853563Z", "versionId": "437", "extension": [{"url": "ex:createdAt", "valueInstant": "2024-08-12T08:07:33.956211Z"}]}, "title": "New form", "status": "draft", "subjectType": ["Patient"], "resourceType": "Questionnaire", "extension": [{"url": "https://jira.hl7.org/browse/FHIR-22356#assembledFrom", "valueCanonical": "4e3ca838-f83b-4489-a5c9-c782824d672d"}]}`

There is an item with extension with value in aidbox format
`"extension": [{"url": "http://hl7.org/fhir/StructureDefinition/questionnaire-unitOption", "value": {"Coding": {"display": "F"}}}]}]`

But requesting trough with no $assemble operation /fhir/Questionnaire/4e3ca838-f83b-4489-a5c9-c782824d672d returns:
`{"subjectType":["Patient"],"meta":{"profile":["https://beda.software/beda-emr-questionnaire"],"lastUpdated":"2024-08-13T11:47:15.853563Z","versionId":"437","extension":[{"url":"ex:createdAt","valueInstant":"2024-08-12T08:07:33.956211Z"}]},"item":[{"text":"Quantity Input","type":"quantity","linkId":"pyxzJPuJ","extension":[{"url":"http://hl7.org/fhir/StructureDefinition/questionnaire-unitOption","valueCoding":{"display":"F"}}]}],"resourceType":"Questionnaire","title":"New form","status":"draft","id":"4e3ca838-f83b-4489-a5c9-c782824d672d","url":"http://forms.aidbox.io/questionnaire/new-form"}`

Result with an extension in fhir format
`"extension":[{"url":"http://hl7.org/fhir/StructureDefinition/questionnaire-unitOption","valueCoding":{"display":"F"}}]}]`

**Uses:**
image: healthsamurai/aidboxone:stable

**Comment by ir4y** [comment]
Use https://docs.aidbox.app/api-1/api/usdto-format-fhir-aidbox instead of python converters for all operations in https://github.com/beda-software/fhir-sdc/blob/master/app/aidbox/operations.py

**Comment by ruscoder** [comment]
Looks like it was fixed, closing
